### ISSUE TITLE
Update eventsInS3ToSplunk.yml required

### ISSUE THREAD

**Issue by josecarlosfl18** [pdreeves/splunk-aws-gdi-toolkit#14]
After follow up the steps to deploy the function, several extra steps are require while not documented:

1- Mandatory fields: 
 - logType, 
 - splunkHECEndpoint, 
 - splunkHECToken, 
 - splunkHost, 
 - splunkIndex, 
 - splunkSource, 
 - splunkSourcetype, 
 - stack-name, 
 - capabilities

For such parameter-overrides, the following values were used: 
 - elblog, 
 - https://http-inputs-firehose-customized-name.splunkcloud.com/services/collector
 - secret-hash
 - loremIpsunDolor
 - netlb
 - s3-bucket-with-access-logs-unmanaged
 - aws:elb:accesslogs
 - aws-to-splunk-app-test-latest
 - CAPABILITY_NAMED_IAM
 
 2- The final deploy command like looks like: 
 
 aws cloudformation deploy  \
    --template $(pwd)/eventsInS3ToSplunk.yml \
    --parameter-overrides \
        logType=elblog \
        splunkHECEndpoint='https://http-inputs-firehose-customized-name.splunkcloud.com/services/collector' \
        splunkHECTokensecret-hasg\
        splunkHost=loremIpsunDolor \
        splunkIndex=netlb \
        splunkSource=s3-bucket-with-access-logs-unmanaged \
        splunkSourcetype=aws:elb:accesslogs \
    --stack-name aws-to-splunk-app-test-latest \
    --capabilities CAPABILITY_NAMED_IAM
    
3- After a successful deploy, the function start giving errors in the Lambda console like: 

```
No more records within selected time range Retry
--
  | 2022-12-19T11:43:18.146-05:00 | START RequestId: d2300018-a8e8-5655-bb5a-5c023e2bf384 Version: $LATEST
  | 2022-12-19T11:43:18.148-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:43:18.150-05:00 | END RequestId: d2300018-a8e8-5655-bb5a-5c023e2bf384
  | 2022-12-19T11:43:18.150-05:00 | REPORT RequestId: d2300018-a8e8-5655-bb5a-5c023e2bf384 Duration: 3.46 ms Billed Duration: 4 ms Memory Size: 1024 MB Max Memory Used: 53 MB Init Duration: 233.69 ms
  | 2022-12-19T11:43:18.641-05:00 | START RequestId: 7a8ad0f3-33cb-5f03-b28a-8ce9a502d968 Version: $LATEST
  | 2022-12-19T11:43:18.642-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:43:18.643-05:00 | END RequestId: 7a8ad0f3-33cb-5f03-b28a-8ce9a502d968
  | 2022-12-19T11:43:18.643-05:00 | REPORT RequestId: 7a8ad0f3-33cb-5f03-b28a-8ce9a502d968 Duration: 1.91 ms Billed Duration: 2 ms Memory Size: 1024 MB Max Memory Used: 53 MB
  | 2022-12-19T11:44:50.741-05:00 | START RequestId: 6c1c4e98-cdb5-5ed8-a31a-12825aaab0f1 Version: $LATEST
  | 2022-12-19T11:44:50.742-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:44:50.743-05:00 | END RequestId: 6c1c4e98-cdb5-5ed8-a31a-12825aaab0f1
  | 2022-12-19T11:44:50.743-05:00 | REPORT RequestId: 6c1c4e98-cdb5-5ed8-a31a-12825aaab0f1 Duration: 1.72 ms Billed Duration: 2 ms Memory Size: 1024 MB Max Memory Used: 54 MB
  | 2022-12-19T11:44:51.977-05:00 | START RequestId: 99b6151d-50f5-5561-b990-4907c7dff129 Version: $LATEST
  | 2022-12-19T11:44:51.978-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:44:51.979-05:00 | END RequestId: 99b6151d-50f5-5561-b990-4907c7dff129
  | 2022-12-19T11:44:51.979-05:00 | REPORT RequestId: 99b6151d-50f5-5561-b990-4907c7dff129 Duration: 1.75 ms Billed Duration: 2 ms Memory Size: 1024 MB Max Memory Used: 54 MB
  | 2022-12-19T11:44:52.508-05:00CopySTART RequestId: f29659d1-1620-56e4-8197-05cb810c24c3 Version: $LATEST | START RequestId: f29659d1-1620-56e4-8197-05cb810c24c3 Version: $LATEST
  | 2022-12-19T11:44:52.510-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:44:52.511-05:00 | END RequestId: f29659d1-1620-56e4-8197-05cb810c24c3
  | 2022-12-19T11:44:52.511-05:00 | REPORT RequestId: f29659d1-1620-56e4-8197-05cb810c24c3 Duration: 3.73 ms Billed Duration: 4 ms Memory Size: 1024 MB Max Memory Used: 54 MB
  | 2022-12-19T11:45:18.030-05:00 | START RequestId: 280f73fc-8981-598b-bc67-2fe61ecc5b0c Version: $LATEST
  | 2022-12-19T11:45:18.031-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:45:18.031-05:00 | END RequestId: 280f73fc-8981-598b-bc67-2fe61ecc5b0c
  | 2022-12-19T11:45:18.031-05:00 | REPORT RequestId: 280f73fc-8981-598b-bc67-2fe61ecc5b0c Duration: 1.69 ms Billed Duration: 2 ms Memory Size: 1024 MB Max Memory Used: 54 MB
  | 2022-12-19T11:45:18.705-05:00 | START RequestId: 32d43449-eb7d-5bec-ac92-68537c4090e3 Version: $LATEST
  | 2022-12-19T11:45:18.706-05:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'pandas' Traceback (most recent call last):
  | 2022-12-19T11:45:18.707-05:00 | END RequestId: 32d43449-eb7d-5bec-ac92-68537c4090e3
```
 
Is something outdated, or prior to do (kinda dependencies) before the function proper work?

**Comment by josecarlosfl18** [comment]
Thanks for the update.

I proceed to do the update, and now I got this comming in the console:

`
-- | --
  | 2022-12-20T12:29:21.342-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.342-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.342-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.342-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.351-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.351-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.388-05:00 | Processed file s3://xxxxxxxxxxxx-us-west-2-elblog/arms/AWSLogs/xxxxxxxxxxxx/elasticloadbalancing/us-west-2/2022/12/18/xxxxxxxxxxxx_elasticloadbalancing_us-west-2_app.xxxxx.f5d69d8e559eec82_20221218T0805Z_10.128.3.227_4pt9me9a.log.gz
  | 2022-12-20T12:29:21.467-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.467-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.478-05:00 | Processed file s3://xxxxxxxxxxxx-us-west-2-elblog/arms/AWSLogs/xxxxxxxxxxxx/elasticloadbalancing/us-west-2/2022/12/18/xxxxxxxxxxxx_elasticloadbalancing_us-west-2_app.xxxxx.f5d69d8e559eec82_20221218T0805Z_10.128.1.4_2gcpog9s.log.gz
  | 2022-12-20T12:29:21.532-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.532-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.532-05:00 | Unable to extract timestamp. Falling back to current time.
  | 2022-12-20T12:29:21.541-05:00 | Processed file s3://xxxxxxxxxxxx-us-west-2-elblog/arms/AWSLogs/xxxxxxxxxxxx/elasticloadbalancing/us-west-2/2022/12/17/896552222739_elasticloadbalancing_us-west-2_app.xxxxx.f5d69d8e559eec82_20221217T1105Z_10.128.2.146_514m7xgn.log.gz
  | 2022-12-20T12:29:21.612-05:00 | Unable to extract timestamp. Falling back to current time.

`

I just want to validate if this is the expected output of the logs?.

**Comment by pdreeves** [comment]
Nope, that's not expected.  That error message indicates the function couldn't extract the timestamp.  I'd recommend making sure that the CloudFormation template was deployed with the setting specified in [the documentation](https://github.com/pdreeves/splunk-aws-gdi-toolkit/wiki/S3-SQS-Lambda-Firehose-Method#elb-access-log-deployment-instructions), specifically the appropriate settings for the `splunkTimeDelineatedField` and `splunkTimeFormat` parameters.

Also, I did fix the issue of Lambda importing pandas and pyarrow in a more permanent way.  Thanks again for pointing that one out!

**Comment by josecarlosfl18** [comment]
Hello, related to the error **Unable to extract timestamp. Falling back to current time** is related to there is a prefix that comes in the log, the prefix changes to different values, a space, and then the timestamp in the ISO format. If I delete the **(.{1,5})?** part of the regex in the prefix-ISO8601 format, then it works with the regexgroupindex of 0 (no splunk prefix, since it dynamic not fixed). How can you suggest to approach this?

Considering that having a customized regex would be a bad practice. The prefix can be strings like 

- h2 2022-12-30T15:08:29.240935Z 
- https 2022-12-30T15:05:25.942645Z
- 2022-12-30T15:08:30.114770Z

So, we can adjust the regex to fit this prefix of up-to 10 char length or empty-non-exist?

**Comment by pdreeves** [comment]
Hello!  Since the [ELB](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html)/[ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html)/[NLB](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html#access-log-entry-format) logs are delimited by spaces, I'd follow the [specified documentation](https://github.com/pdreeves/splunk-aws-gdi-toolkit/wiki/S3-SQS-Lambda-Firehose-Method#elb-access-log-deployment-instructions) for these log types.  Specifically by setting the `splunkEventDelimiter` to `space`, `splunkTimeDelineatedField` to `1` for ALB logs or `0` for ELB logs or `2` for NLB logs, and `splunkTimeFormat` to `delineated-ISO8601`.

I'll get the wiki instructions updated to reflect that a setting of `1` should be used for ALB logs, `0` for ELB logs and `2` for NLB logs should be used for the `splunkTimeDelineatedField` parameter on the CFT.  Thanks for pointing that out!

**Comment by pdreeves** [comment]
Documentation updated!
